import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  developmentSidebar: [
    { type: 'doc', id: 'development/index', label: 'Développement' },
    'development/postgres',
    'development/vim',
    'development/git',
    'development/log',
  ],
  cuisineSidebar: [
    { type: 'doc', id: 'cuisine/index', label: 'Cuisine' },
    { type: 'autogenerated', dirName: 'cuisine/recettes' },
  ],
}

export default sidebars
